#!/bin/sh
set -eu

API_BASE_URL="${PACKT_API_BASE_URL:-}"
AUTO_RECHECK_ENABLED="${PACKT_AUTO_RECHECK_ENABLED:-true}"
AUTO_RECHECK_INTERVAL_MS="${PACKT_AUTO_RECHECK_INTERVAL_MS:-14400000}"
ESCAPED_API_BASE_URL=$(printf '%s' "$API_BASE_URL" | sed 's/\\/\\\\/g; s/"/\\"/g')
ESCAPED_AUTO_RECHECK_ENABLED=$(printf '%s' "$AUTO_RECHECK_ENABLED" | sed 's/\\/\\\\/g; s/"/\\"/g')
ESCAPED_AUTO_RECHECK_INTERVAL_MS=$(printf '%s' "$AUTO_RECHECK_INTERVAL_MS" | sed 's/\\/\\\\/g; s/"/\\"/g')

cat > /usr/share/nginx/html/runtime-config.js <<EOF
window.__PACKT_CONFIG__ = {
  API_BASE_URL: "${ESCAPED_API_BASE_URL}",
  AUTO_RECHECK_ENABLED: "${ESCAPED_AUTO_RECHECK_ENABLED}",
  AUTO_RECHECK_INTERVAL_MS: "${ESCAPED_AUTO_RECHECK_INTERVAL_MS}"
};
EOF
